AllowedHosts: '*'

Serilog:
  Enrich: [ 'FromLogContext' ]
  MinimumLevel:
    Default: 'Warning'
    Override:
      Microsoft.AspNetCore: 'Warning'
      Microsoft.EntityFrameworkCore: 'Warning'
      System.Net.Http.HttpClient: 'Warning'
  WriteTo:
    - Name: 'Console'
      Args:
        OutputTemplate: '[{Timestamp:HH:mm:ss}] [{Level:u3}] [{SourceContext}] {Message:lj}{NewLine}{Exception}'

Application:
  EnableSwagger: false

Telegram:
  AccessToken:
  SecretKey:

Vk:
  AccessToken:
  SecretKey:
  ConfirmationCode:
  LongPolling:
    GroupId: 146048760
    WaitTimeout: 25
    DelayBetweenUpdates: '00:00:00.250'

Clients:
  Narfu:
    HostUrl: 'https://ruz.narfu.ru/'
    Timeout: '00:00:05'
    GroupsRefreshInterval: '12:00:00'
  OpenWeatherMap:
    HostUrl: 'https://api.openweathermap.org/data/2.5/'
    AccessToken:
    Timeout: '00:00:05'
    Language: 'ru'
    Units: 'metric'

Mailing:
  Schedule:
    IsEnabled: true
    # запускается в 6:05 с понедельника по субботу весь год, кроме августа
    CronExpression: '0 5 6 ? 1-7,9-12 MON-SAT'
  Weather:
    IsEnabled: true
    # запускается в 6:30 каждый день
    CronExpression: '0 30 6 ? * *'
