// <auto-generated />
using System;
using Goblin.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Goblin.Persistence.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class d9o30apvvh50ejContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Goblin.Domain.Entities.RecurringJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Conversation");

                    b.Property<int>("Hours");

                    b.Property<string>("JobName");

                    b.Property<int>("Minutes");

                    b.Property<int>("NarfuGroup");

                    b.Property<string>("WeatherCity");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.Remind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Text");

                    b.Property<long>("VkId");

                    b.HasKey("Id");

                    b.ToTable("Reminds");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.BotUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("Group");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsErrorsDisabled");

                    b.Property<bool>("Schedule");

                    b.Property<long>("Vk");

                    b.Property<bool>("Weather");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
