// <auto-generated />
using System;
using Goblin.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Goblin.DataAccess.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260815180703_InitBotV4")]
    partial class InitBotV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Goblin.Domain.Entities.BotUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsumerType")
                        .HasColumnType("integer");

                    b.Property<bool>("HasScheduleSubscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasWeatherSubscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsErrorsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("NarfuGroup")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerType", "ConsumerId");

                    b.ToTable("BotUsers");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.BotUserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlowStepType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FlowType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotUserId")
                        .IsUnique();

                    b.ToTable("BotUserSessions");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.CronJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsumerType")
                        .HasColumnType("integer");

                    b.Property<int>("CronType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NarfuGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WeatherCity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CronJobs");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.Remind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BotUserId");

                    b.ToTable("Reminds");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.BotUserSession", b =>
                {
                    b.HasOne("Goblin.Domain.Entities.BotUser", "BotUser")
                        .WithOne("Session")
                        .HasForeignKey("Goblin.Domain.Entities.BotUserSession", "BotUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotUser");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.CronJob", b =>
                {
                    b.OwnsOne("Goblin.Domain.CronTime", "Time", b1 =>
                        {
                            b1.Property<Guid>("CronJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DayOfMonth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Hour")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Minute")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Month")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CronJobId");

                            b1.ToTable("CronJobs");

                            b1.WithOwner()
                                .HasForeignKey("CronJobId");
                        });

                    b.Navigation("Time")
                        .IsRequired();
                });

            modelBuilder.Entity("Goblin.Domain.Entities.Remind", b =>
                {
                    b.HasOne("Goblin.Domain.Entities.BotUser", "BotUser")
                        .WithMany("Reminds")
                        .HasForeignKey("BotUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotUser");
                });

            modelBuilder.Entity("Goblin.Domain.Entities.BotUser", b =>
                {
                    b.Navigation("Reminds");

                    b.Navigation("Session")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
